
---
include:
  # left
  - board: seeeduino_xiao_ble
    shield: cygnus_left

  # right
  - board: seeeduino_xiao_ble
    shield: cygnus_right


  # dongle
  - board: seeeduino_xiao
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    shield: cygnus_dongle 

  # reset
  - board: seeeduino_xiao
    shield: settings_reset


